(function(){
'use strict';
var SB_URL='https://burtvenqfzextswpjziw.supabase.co';
var SB_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1cnR2ZW5xZnpleHRzd3Bqeml3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUyNTkxMzEsImV4cCI6MjA5MDgzNTEzMX0.M9krIdktkO1wMeKYMm_HoR_tEykewbRUVHdjerg1XIo';
var state=null, session=null, current=null, timer=null;
function $(id){return document.getElementById(id);} function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function deep(x){return JSON.parse(JSON.stringify(x));}
function toast(s){var t=$('toast'); t.textContent=s; t.classList.add('show'); setTimeout(function(){t.classList.remove('show')},1800);}
function auth(){try{return JSON.parse(localStorage.getItem('acq_auth')||'null');}catch(e){return null;}}
function uid(){var a=auth(); return a&&a.user&&a.user.id;} function email(){var a=auth(); return a&&a.user&&a.user.email||'';}
function headers(){var a=auth(); return {'Content-Type':'application/json','apikey':SB_KEY,'Authorization':'Bearer '+(a&&a.access_token||SB_KEY)};}
function api(path,opt){opt=opt||{}; opt.headers=Object.assign(headers(),opt.headers||{}); return fetch(SB_URL+path,opt).then(function(r){return r.text().then(function(txt){var d=txt?JSON.parse(txt):null; if(!r.ok)throw new Error((d&&(d.message||d.error_description||d.msg))||r.statusText); return d;});});}
function defaultState(){return {version:'0.1.0',exerciseLibrary:deep(window.RQFIT_PRESET_EXERCISES),routine:deep(window.RQFIT_STARTER_ROUTINE),sessions:[],bodyLog:[],settings:{contractGpBase:25,contractGpPer10Min:5,sounds:true,autoAdvanceRotation:true}};}
function ex(id){return (state.exerciseLibrary||[]).find(function(e){return e.id===id;})||{};}
function plan(dayEx){var e=ex(dayEx.exerciseId); return Object.assign({},e,dayEx,{name:e.name||dayEx.exerciseId,type:e.type||'strength'});}
function restFmt(s){s=Number(s)||0; return Math.floor(s/60)+':'+String(s%60).padStart(2,'0');}
function saveLocal(){localStorage.setItem('rqfit_state:'+uid(),JSON.stringify(state));}
function loadLocal(){try{return JSON.parse(localStorage.getItem('rqfit_state:'+uid())||'null');}catch(e){return null;}}
function syncPull(){ if(!uid()){state=loadLocal()||defaultState(); render(); return Promise.resolve();}
 return api('/rest/v1/rq_training_state?user_id=eq.'+uid()+'&select=state&limit=1').then(function(rows){state=(rows&&rows[0]&&rows[0].state)||loadLocal()||defaultState(); saveLocal(); render();}).catch(function(e){state=loadLocal()||defaultState(); render(); toast('Using local state: '+e.message);});}
function syncPush(){ if(!uid()){saveLocal(); toast('Saved locally. Log into RQ before cloud sync.'); return Promise.resolve();}
 saveLocal(); var body={user_id:uid(),state:state,updated_at:new Date().toISOString()};
 return api('/rest/v1/rq_training_state',{method:'POST',headers:{Prefer:'resolution=merge-duplicates'},body:JSON.stringify(body)}).then(function(){toast('Training synced.');}).catch(function(e){toast('Sync failed: '+e.message);});}
function createContract(sess){ if(!uid())return Promise.resolve(); var mins=Math.max(1,Math.round(sess.durationSec/60)); var gp=(state.settings.contractGpBase||25)+Math.floor(mins/10)*(state.settings.contractGpPer10Min||5); var payload={user_id:uid(),source_session_id:sess.id,title:'🏋️ Completed Workout: '+sess.dayName,gp:Math.min(100,gp),duration_sec:sess.durationSec,workout_date:new Date(sess.endedAt).toISOString().slice(0,10),status:'pending',details:sess}; return api('/rest/v1/rq_training_contracts',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(payload)}).catch(function(e){toast('Workout saved; contract pending failed: '+e.message);}); }
function render(){ $('authLine').textContent=uid()?('Signed in as '+email()):'Open from logged-in Relentless Quest to sync.'; renderToday(); renderWorkout(); renderRoutine(); renderLibrary(); renderHistory(); renderBody(); }
function renderToday(){var ri=(state.routine.rotationIndex||0)%state.routine.days.length, d=state.routine.days[ri]; var last=(state.sessions||[]).slice(-1)[0]; $('today').innerHTML='<div class="row"><div><div class="muted">Next rotation workout</div><div class="exercise-title">'+esc(d.name)+'</div><div class="muted">'+d.exercises.length+' exercises'+(last?' · Last: '+esc(last.dayName):'')+'</div></div><button id="startBtn">Start</button></div>'; $('startBtn').onclick=startWorkout;}
function startWorkout(){RQFitSound.unlock(); var d=state.routine.days[(state.routine.rotationIndex||0)%state.routine.days.length]; current={id:'w'+Date.now().toString(36),dayId:d.id,dayName:d.name,startedAt:new Date().toISOString(),exerciseIndex:0,logs:[],skipped:[],finished:false}; renderWorkout(); toast('Workout started.');}
function activeExercise(){if(!current)return null; var d=state.routine.days.find(function(x){return x.id===current.dayId;}); return d&&d.exercises[current.exerciseIndex];}
function renderWorkout(){var box=$('tab-workout'); if(!current){var d=state.routine.days[(state.routine.rotationIndex||0)%state.routine.days.length]; box.innerHTML='<div class="panel"><h2>Ready</h2><p class="muted">Next workout: '+esc(d.name)+'. Rotation-based, not calendar-locked.</p><button class="wide" onclick="RQFit.startWorkout()">Start Next Workout</button></div>';return;}
 var pe=activeExercise(); if(!pe){finishWorkout();return;} var e=plan(pe), logs=current.logs.filter(function(l){return l.exerciseId===pe.exerciseId&&l.exerciseOrder===current.exerciseIndex;}); var target=e.type==='cardio'?(e.durationSec||300)+' sec':(pe.sets||e.defaultSets||3)+' × '+(pe.reps||e.defaultReps||8)+' @ '+(pe.weight||e.defaultWeight||0)+' lb';
 var rows=logs.map(function(l,i){return '<div class="setbox">Set '+(i+1)+'<br><b>'+esc(l.weight||'')+' lb × '+esc(l.reps||'')+'</b></div>';}).join('');
 box.innerHTML='<div class="panel"><div class="muted">Exercise '+(current.exerciseIndex+1)+'</div><div class="exercise-title">'+esc(e.name)+'</div><div class="muted">Target: '+esc(target)+' · Rest '+restFmt(pe.restSec||e.defaultRestSec||0)+'</div>'+demoHtml(e)+'<div id="timer" class="timer">Ready</div><div class="grid two">'+numBtn('weight','Weight',pe.weight||e.defaultWeight||0,'lb')+numBtn('reps','Reps',pe.reps||e.defaultReps||0,'')+numBtn('sets','Sets',pe.sets||e.defaultSets||0,'')+numBtn('restSec','Rest',pe.restSec||e.defaultRestSec||0,'sec')+'</div><div class="setlog">'+(rows||'<div class="muted">No sets logged yet.</div>')+'</div><div class="grid two" style="margin-top:12px"><button id="logSet" class="gold">Log Set</button><button id="skipEx" class="ghost">Skip Exercise</button><button id="nextEx">Finish Exercise</button><button id="endWorkout" class="danger">End Workout</button></div></div>';
 document.querySelectorAll('[data-adj]').forEach(function(b){b.onclick=function(){adjust(pe,b.dataset.field,Number(b.dataset.adj));};}); $('logSet').onclick=function(){logSet(pe,e,logs.length);}; $('skipEx').onclick=function(){current.skipped.push({exerciseId:pe.exerciseId,name:e.name,at:new Date().toISOString()}); nextExercise();}; $('nextEx').onclick=nextExercise; $('endWorkout').onclick=finishWorkout;}
function demoHtml(e){ if(e.localDemoPath)return '<div class="demo-frame"><img src="'+esc(e.localDemoPath)+'" alt="'+esc(e.name)+' demo"></div>'; if(e.sourceUrl)return '<p><a class="linkbtn" target="_blank" rel="noopener" href="'+esc(e.sourceUrl)+'">View demo/reference</a></p>'; return '';}
function numBtn(field,label,val,suf){return '<div class="card"><div class="muted">'+label+'</div><div class="bigstat">'+esc(val)+'</div><div class="row"><button class="small" data-field="'+field+'" data-adj="-1">−</button><span>'+esc(suf)+'</span><button class="small" data-field="'+field+'" data-adj="1">+</button></div></div>';}
function adjust(pe,field,delta){var step=field==='restSec'?5:1; pe[field]=Math.max(0,(Number(pe[field])||0)+delta*step); saveLocal(); renderWorkout();}
function logSet(pe,e,done){RQFitSound.setLogged(); var log={exerciseId:pe.exerciseId,exerciseName:e.name,exerciseOrder:current.exerciseIndex,setNo:done+1,weight:pe.weight||e.defaultWeight||0,reps:pe.reps||e.defaultReps||0,at:new Date().toISOString()}; current.logs.push(log); var target=pe.sets||e.defaultSets||1; saveLocal(); if(done+1>=target){toast('Exercise target complete.'); renderWorkout();} else startRest(pe.restSec||e.defaultRestSec||0);}
function startRest(sec){clearInterval(timer); var left=Number(sec)||0; if(RQFitSound)RQFitSound.restStart(); timer=setInterval(function(){var t=$('timer'); if(t)t.textContent=restFmt(left); if(left===30)RQFitSound.warn(); if(left<=5&&left>0)RQFitSound.countdown(); if(left<=0){clearInterval(timer); RQFitSound.ready(); var tt=$('timer'); if(tt)tt.textContent='Next set'; return;} left--;},1000);}
function nextExercise(){clearInterval(timer); current.exerciseIndex++; saveLocal(); renderWorkout();}
function finishWorkout(){if(!current)return; clearInterval(timer); current.endedAt=new Date().toISOString(); current.durationSec=Math.max(1,Math.round((new Date(current.endedAt)-new Date(current.startedAt))/1000)); current.finished=true; state.sessions.push(current); if(state.sessions.length>300)state.sessions=state.sessions.slice(-300); if(state.settings.autoAdvanceRotation!==false)state.routine.rotationIndex=((state.routine.rotationIndex||0)+1)%state.routine.days.length; var finished=current; current=null; saveLocal(); syncPush().then(function(){return createContract(finished);}).then(function(){RQFitSound.complete(); toast('Workout complete. Contract queued for RQ.'); render();});}
function renderRoutine(){var html='<div class="panel"><h2>Routine Rotation</h2><p class="muted">Exercises stay in order. You can skip during workouts, but this screen edits the plan.</p></div>'; state.routine.days.forEach(function(d,di){html+='<div class="card"><div class="row"><h3>'+esc(d.name)+'</h3><button class="small" data-day="'+di+'" data-addex>Add Exercise</button></div>'; d.exercises.forEach(function(pe,ei){var e=plan(pe); html+='<div class="card"><b>'+esc(e.name)+'</b><div class="muted">'+(e.type==='cardio'?esc(pe.durationSec||e.defaultDurationSec||0)+' sec':esc(pe.weight||0)+' lb · '+esc(pe.sets||0)+' sets · '+esc(pe.reps||0)+' reps · rest '+restFmt(pe.restSec||0))+'</div><button class="small danger" data-del="'+di+','+ei+'">Remove</button></div>';}); html+='</div>';}); $('tab-routine').innerHTML=html; document.querySelectorAll('[data-del]').forEach(function(b){b.onclick=function(){var p=b.dataset.del.split(',').map(Number); state.routine.days[p[0]].exercises.splice(p[1],1); saveLocal(); render();};}); document.querySelectorAll('[data-addex]').forEach(function(b){b.onclick=function(){var id=prompt('Exercise id to add (see Library):'); if(!id)return; var e=ex(id); if(!e.id)return alert('Unknown exercise id.'); state.routine.days[Number(b.dataset.day)].exercises.push({exerciseId:id,weight:e.defaultWeight||0,sets:e.defaultSets||1,reps:e.defaultReps||0,restSec:e.defaultRestSec||0,durationSec:e.defaultDurationSec}); saveLocal(); render();};});}
function renderLibrary(){var html='<div class="panel"><h2>Exercise Library</h2><p class="muted">Media is local/custom only. ExRx links open as references rather than hotlinked GIFs.</p></div>'; state.exerciseLibrary.forEach(function(e){html+='<div class="card"><div class="row"><div><b>'+esc(e.name)+'</b><div class="muted">ID: '+esc(e.id)+' · '+esc(e.type)+'</div></div>'+(e.sourceUrl?'<a class="linkbtn" target="_blank" href="'+esc(e.sourceUrl)+'">Reference</a>':'')+'</div>'+(e.equipment||[]).map(function(x){return '<span class="pill">'+esc(x)+'</span>';}).join('')+'</div>';}); $('tab-library').innerHTML=html;}
function renderHistory(){var ss=(state.sessions||[]).slice().reverse(); var html='<div class="panel"><h2>History</h2><p class="muted">'+ss.length+' workout sessions logged.</p></div>'; ss.slice(0,30).forEach(function(s){html+='<div class="card"><b>'+esc(s.dayName)+'</b><div class="muted">'+new Date(s.endedAt).toLocaleString()+' · '+Math.round(s.durationSec/60)+' min · '+(s.logs||[]).length+' sets</div></div>';}); $('tab-history').innerHTML=html;}
function renderBody(){var html='<div class="panel"><h2>Body Measurements</h2><div class="grid two"><label>Body weight<input id="bodyWeight" inputmode="decimal"></label><label>Waist<input id="waist" inputmode="decimal"></label><label>Bicep<input id="bicep" inputmode="decimal"></label><label>Chest<input id="chest" inputmode="decimal"></label><label>Thigh<input id="thigh" inputmode="decimal"></label><label>Notes<input id="bodyNotes"></label></div><button id="saveBody" class="wide" style="margin-top:10px">Log Measurements</button></div>'; (state.bodyLog||[]).slice().reverse().slice(0,20).forEach(function(b){html+='<div class="card"><b>'+new Date(b.at).toLocaleDateString()+'</b><div class="muted">Weight '+esc(b.weight||'—')+' · Waist '+esc(b.waist||'—')+' · Bicep '+esc(b.bicep||'—')+'</div><div>'+esc(b.notes||'')+'</div></div>';}); $('tab-body').innerHTML=html; $('saveBody').onclick=function(){state.bodyLog.push({at:new Date().toISOString(),weight:$('bodyWeight').value,waist:$('waist').value,bicep:$('bicep').value,chest:$('chest').value,thigh:$('thigh').value,notes:$('bodyNotes').value}); saveLocal(); syncPush(); render();};}
function bind(){ $('backToRq').onclick=function(){location.href='../relentless-quest-in-development.html';}; $('syncBtn').onclick=function(){syncPush();}; document.querySelectorAll('.tabs button').forEach(function(b){b.onclick=function(){document.querySelectorAll('.tabs button').forEach(function(x){x.classList.remove('active')}); b.classList.add('active'); document.querySelectorAll('.tab-panel').forEach(function(x){x.classList.add('hidden')}); $('tab-'+b.dataset.tab).classList.remove('hidden');};});}
window.RQFit={startWorkout:startWorkout}; bind(); syncPull();
})();
