(function(){
'use strict';
var SB_URL='https://burtvenqfzextswpjziw.supabase.co';
var SB_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1cnR2ZW5xZnpleHRzd3Bqeml3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUyNTkxMzEsImV4cCI6MjA5MDgzNTEzMX0.M9krIdktkO1wMeKYMm_HoR_tEykewbRUVHdjerg1XIo';
var state=null, current=null, timer=null;
var routineCollapsed={};
function $(id){return document.getElementById(id);} function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function deep(x){return JSON.parse(JSON.stringify(x));}
function toast(s){var t=$('toast'); if(!t)return; t.textContent=s; t.classList.add('show'); setTimeout(function(){t.classList.remove('show')},1800);}
function auth(){try{return JSON.parse(localStorage.getItem('acq_auth')||'null');}catch(e){return null;}}
function uid(){var a=auth(); return a&&a.user&&a.user.id;} function email(){var a=auth(); return a&&a.user&&a.user.email||'';}
function headers(){var a=auth(); return {'Content-Type':'application/json','apikey':SB_KEY,'Authorization':'Bearer '+(a&&a.access_token||SB_KEY)};}
function api(path,opt){opt=opt||{}; opt.headers=Object.assign(headers(),opt.headers||{}); return fetch(SB_URL+path,opt).then(function(r){return r.text().then(function(txt){var d=txt?JSON.parse(txt):null; if(!r.ok)throw new Error((d&&(d.message||d.error_description||d.msg))||r.statusText); return d;});});}
function defaultState(){return migrateState({version:'0.1.6',exerciseLibrary:deep(window.RQFIT_PRESET_EXERCISES||[]),routine:deep(window.RQFIT_STARTER_ROUTINE||{rotationIndex:0,days:[]}),sessions:[],bodyLog:[],settings:{contractGpBase:25,contractGpPer10Min:5,sounds:true,autoAdvanceRotation:true}});}
function migrateState(s){s=s||{}; s.version='0.1.6'; s.exerciseLibrary=s.exerciseLibrary||deep(window.RQFIT_PRESET_EXERCISES||[]); s.routine=s.routine||deep(window.RQFIT_STARTER_ROUTINE||{rotationIndex:0,days:[]}); s.routine.rotationIndex=Number(s.routine.rotationIndex)||0; s.routine.days=(s.routine.days||[]).map(function(d,i){d=d||{}; d.id=d.id||('routine-'+Date.now().toString(36)+'-'+i); d.name=d.name||('Routine '+(i+1)); if(typeof d.active==='undefined')d.active=true; d.exercises=d.exercises||[]; return d;}); s.sessions=s.sessions||[]; s.bodyLog=s.bodyLog||[]; s.settings=Object.assign({contractGpBase:25,contractGpPer10Min:5,sounds:true,autoAdvanceRotation:true},s.settings||{}); return s;}
function ex(id){return (state.exerciseLibrary||[]).find(function(e){return e.id===id;})||{};}
function plan(dayEx){var e=ex(dayEx.exerciseId); return Object.assign({},e,dayEx,{name:e.name||dayEx.exerciseId,type:e.type||'strength'});}
function restFmt(s){s=Number(s)||0; return Math.floor(s/60)+':'+String(s%60).padStart(2,'0');}
function saveLocal(){localStorage.setItem('rqfit_state:'+uid(),JSON.stringify(state));}
function loadLocal(){try{return JSON.parse(localStorage.getItem('rqfit_state:'+uid())||'null');}catch(e){return null;}}
function syncPull(){ if(!uid()){state=migrateState(loadLocal()||defaultState()); render(); return Promise.resolve();}
 return api('/rest/v1/rq_training_state?user_id=eq.'+uid()+'&select=state&limit=1').then(function(rows){state=migrateState((rows&&rows[0]&&rows[0].state)||loadLocal()||defaultState()); saveLocal(); render();}).catch(function(e){state=migrateState(loadLocal()||defaultState()); render(); toast('Using local state: '+e.message);});}
function syncPush(){ if(!uid()){saveLocal(); toast('Saved locally. Log into RQ before cloud sync.'); return Promise.resolve();}
 saveLocal(); var body={user_id:uid(),state:state,updated_at:new Date().toISOString()};
 return api('/rest/v1/rq_training_state',{method:'POST',headers:{Prefer:'resolution=merge-duplicates'},body:JSON.stringify(body)}).then(function(){toast('Training synced.');}).catch(function(e){toast('Sync failed: '+e.message);});}
function createContract(sess){ if(!uid())return Promise.resolve(); var mins=Math.max(1,Math.round(sess.durationSec/60)); var gp=(state.settings.contractGpBase||25)+Math.floor(mins/10)*(state.settings.contractGpPer10Min||5); var payload={user_id:uid(),source_session_id:sess.id,title:'🏋️ Completed Workout: '+sess.dayName,gp:Math.min(100,gp),duration_sec:sess.durationSec,workout_date:new Date(sess.endedAt).toISOString().slice(0,10),status:'pending',details:sess}; return api('/rest/v1/rq_training_contracts',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(payload)}).catch(function(e){toast('Workout saved; contract pending failed: '+e.message);}); }
function activeDays(){return (state.routine.days||[]).filter(function(d){return d.active!==false;});}
function nextDay(){var days=activeDays(); if(!days.length)return null; var idx=(Number(state.routine.rotationIndex)||0)%days.length; return days[idx];}
function exerciseChoiceHtml(){return (state.exerciseLibrary||[]).slice().sort(function(a,b){return String(a.name).localeCompare(String(b.name));}).map(function(e){return '<option value="'+esc(e.id)+'">'+esc(e.name)+' — '+esc((e.equipment||[]).join(', '))+'</option>';}).join('');}
function render(){ $('authLine').textContent=uid()?('Signed in as '+email()):'Open from logged-in Relentless Quest to sync.'; renderToday(); renderWorkout(); renderRoutine(); renderLibrary(); renderHistory(); renderBody(); }
function renderToday(){var d=nextDay(); var last=(state.sessions||[]).slice(-1)[0]; if(!d){$('today').innerHTML='<div class="row"><div><div class="muted">No active routines</div><div class="exercise-title">Reactivate or create a routine</div><div class="muted">Sidelined routines are saved, but skipped in rotation.</div></div></div>'; return;} $('today').innerHTML='<div><div class="row"><div><div class="muted">Next active rotation workout</div><div class="exercise-title">'+esc(d.name)+'</div><div class="muted">'+d.exercises.length+' exercises · '+activeDays().length+' active routine(s)'+(last?' · Last: '+esc(last.dayName):'')+'</div></div></div><div class="workout-start-actions"><button id="startBtn" class="gold">Start</button><button id="skipWorkoutToday" class="ghost">Skip Workout</button></div></div>'; $('startBtn').onclick=startWorkout; $('skipWorkoutToday').onclick=skipNextWorkout;}
function startWorkout(){RQFitSound.unlock(); var d=nextDay(); if(!d){toast('No active routine available.'); return;} current={id:'w'+Date.now().toString(36),dayId:d.id,dayName:d.name,startedAt:new Date().toISOString(),exerciseIndex:0,logs:[],skipped:[],finished:false}; renderWorkout(); toast('Workout started.');}
function activeExercise(){if(!current)return null; var d=state.routine.days.find(function(x){return x.id===current.dayId;}); return d&&d.exercises[current.exerciseIndex];}
function renderWorkout(){var box=$('tab-workout'); if(!current){var d=nextDay(); box.innerHTML='<div class="panel"><h2>Ready</h2><p class="muted">Next workout: '+esc(d?d.name:'No active routine')+'. Rotation-based, not calendar-locked.</p><div class="workout-start-actions"><button class="wide gold" id="workoutStartNext" onclick="RQFit.startWorkout()" '+(d?'':'disabled')+'>Start Next Workout</button><button class="wide ghost" id="workoutSkipNext" onclick="RQFit.skipNextWorkout()" '+(d?'':'disabled')+'>Skip This Workout</button></div><p class="muted">Skipping logs a skipped workout in History and advances the rotation, but does not create a gold contract.</p></div>';return;}
 var pe=activeExercise(); if(!pe){finishWorkout();return;} var e=plan(pe), logs=current.logs.filter(function(l){return l.exerciseId===pe.exerciseId&&l.exerciseOrder===current.exerciseIndex;}); var target=e.type==='cardio'?(e.durationSec||300)+' sec':(pe.sets||e.defaultSets||3)+' × '+(pe.reps||e.defaultReps||8)+' @ '+(pe.weight||e.defaultWeight||0)+' lb';
 var rows=logs.map(function(l,i){return '<div class="setbox">Set '+(i+1)+'<br><b>'+esc(l.weight||'')+' lb × '+esc(l.reps||'')+'</b></div>';}).join('');
 box.innerHTML='<div class="panel"><div class="muted">Exercise '+(current.exerciseIndex+1)+'</div><div class="exercise-title">'+esc(e.name)+'</div><div class="muted">Target: '+esc(target)+' · Rest '+restFmt(pe.restSec||e.defaultRestSec||0)+'</div>'+demoHtml(e)+'<div id="timer" class="timer">Ready</div><div class="grid two">'+numBtn('weight','Weight',pe.weight||e.defaultWeight||0,'lb')+numBtn('reps','Reps',pe.reps||e.defaultReps||0,'')+numBtn('sets','Sets',pe.sets||e.defaultSets||0,'')+numBtn('restSec','Rest',pe.restSec||e.defaultRestSec||0,'sec')+'</div><div class="setlog">'+(rows||'<div class="muted">No sets logged yet.</div>')+'</div><div class="grid two" style="margin-top:12px"><button id="logSet" class="gold">Log Set</button><button id="skipEx" class="ghost">Skip Exercise</button><button id="nextEx">Finish Exercise</button><button id="endWorkout" class="danger">End Workout</button></div></div>';
 document.querySelectorAll('[data-adj]').forEach(function(b){b.onclick=function(){adjust(pe,b.dataset.field,Number(b.dataset.adj));};}); $('logSet').onclick=function(){logSet(pe,e,logs.length);}; $('skipEx').onclick=function(){current.skipped.push({exerciseId:pe.exerciseId,name:e.name,at:new Date().toISOString()}); nextExercise();}; $('nextEx').onclick=nextExercise; $('endWorkout').onclick=finishWorkout;}
function demoHtml(e){ if(e.localDemoPath)return '<div class="demo-frame"><img src="'+esc(e.localDemoPath)+'" alt="'+esc(e.name)+' demo"></div>'; if(e.sourceUrl)return '<p><a class="linkbtn" target="_blank" rel="noopener" href="'+esc(e.sourceUrl)+'">View demo/reference</a></p>'; return '';}
function numBtn(field,label,val,suf){return '<div class="card"><div class="muted">'+label+'</div><div class="bigstat">'+esc(val)+'</div><div class="row"><button class="small" data-field="'+field+'" data-adj="-1">−</button><span>'+esc(suf)+'</span><button class="small" data-field="'+field+'" data-adj="1">+</button></div></div>';}
function adjust(pe,field,delta){var step=field==='restSec'?5:1; pe[field]=Math.max(0,(Number(pe[field])||0)+delta*step); saveLocal(); renderWorkout();}
function logSet(pe,e,done){RQFitSound.setLogged(); var log={exerciseId:pe.exerciseId,exerciseName:e.name,exerciseOrder:current.exerciseIndex,setNo:done+1,weight:pe.weight||e.defaultWeight||0,reps:pe.reps||e.defaultReps||0,at:new Date().toISOString()}; current.logs.push(log); var target=pe.sets||e.defaultSets||1; saveLocal(); if(done+1>=target){toast('Exercise target complete.'); renderWorkout();} else startRest(pe.restSec||e.defaultRestSec||0);}
function startRest(sec){clearInterval(timer); var left=Number(sec)||0; if(RQFitSound)RQFitSound.restStart(); timer=setInterval(function(){var t=$('timer'); if(t)t.textContent=restFmt(left); if(left===30)RQFitSound.warn(); if(left<=5&&left>0)RQFitSound.countdown(); if(left<=0){clearInterval(timer); RQFitSound.ready(); var tt=$('timer'); if(tt)tt.textContent='Next set'; return;} left--;},1000);}
function nextExercise(){clearInterval(timer); current.exerciseIndex++; saveLocal(); renderWorkout();}
function advanceRotation(completedDayId){var days=activeDays(); if(!days.length){state.routine.rotationIndex=0;return;} var completedIdx=days.findIndex(function(d){return d.id===completedDayId;}); state.routine.rotationIndex=((completedIdx<0?state.routine.rotationIndex:completedIdx)+1)%days.length;}
function skipNextWorkout(){RQFitSound.unlock(); var d=nextDay(); if(!d){toast('No active routine available to skip.'); return;} if(!confirm('Skip workout "'+d.name+'" and advance to the next routine?'))return; var now=new Date().toISOString(); var sess={id:'skip'+Date.now().toString(36),dayId:d.id,dayName:d.name,startedAt:now,endedAt:now,durationSec:0,logs:[],skipped:(d.exercises||[]).map(function(pe,i){var e=plan(pe); return {exerciseId:pe.exerciseId,name:e.name,exerciseOrder:i,at:now,reason:'workout_skipped'};}),finished:false,status:'skipped',skippedWorkout:true,skipReason:'manual_skip'}; state.sessions.push(sess); if(state.sessions.length>300)state.sessions=state.sessions.slice(-300); if(state.settings.autoAdvanceRotation!==false)advanceRotation(d.id); saveLocal(); syncPush().then(function(){render(); toast('Workout skipped and logged in History.');});}
function finishWorkout(){if(!current)return; clearInterval(timer); current.endedAt=new Date().toISOString(); current.durationSec=Math.max(1,Math.round((new Date(current.endedAt)-new Date(current.startedAt))/1000)); current.finished=true; state.sessions.push(current); if(state.sessions.length>300)state.sessions=state.sessions.slice(-300); if(state.settings.autoAdvanceRotation!==false)advanceRotation(current.dayId); var finished=current; current=null; saveLocal(); syncPush().then(function(){return createContract(finished);}).then(function(){RQFitSound.complete(); toast('Workout complete. Contract queued for RQ.'); render();});}
function routineStats(d){return (d.exercises||[]).length+' exercise'+((d.exercises||[]).length===1?'':'s')+(d.active===false?' · sidelined':' · active');}
function isRoutineCollapsed(id){return routineCollapsed[id]!==false;}
function renderRoutine(){var html='<div class="panel"><h2>Routine Rotation</h2><p class="muted">Active routines are used in the rotation. Sidelined routines stay saved for later but are skipped. Routines start collapsed each page load.</p><div class="grid two"><button id="newRoutine" class="gold">Create New Routine</button><button id="syncRoutine" class="ghost">Save / Sync</button></div></div>'; if(!state.routine.days.length)html+='<div class="card muted">No routines yet. Create one to begin.</div>';
 state.routine.days.forEach(function(d,di){var collapsed=isRoutineCollapsed(d.id); var isActive=d.active!==false; html+='<div class="card routine-card '+(isActive?'':'is-sidelined')+'"><div class="row"><div><h3>'+esc(d.name)+'</h3><div class="muted">'+esc(routineStats(d))+'</div></div><button class="small status-toggle '+(isActive?'gold':'ghost')+'" type="button" data-routine-toggle="'+di+'" title="'+(isActive?'Click to sideline this routine':'Click to return this routine to rotation')+'">'+(isActive?'Active — Sideline':'Sidelined — Reactivate')+'</button></div><div class="routine-actions"><button class="small" data-collapse-routine="'+di+'">'+(collapsed?'Expand':'Collapse')+'</button><button class="small" data-routine-up="'+di+'">↑ Routine</button><button class="small" data-routine-down="'+di+'">↓ Routine</button><button class="small" data-routine-rename="'+di+'">Rename</button><button class="small '+(isActive?'ghost':'gold')+'" data-routine-toggle="'+di+'">'+(isActive?'Sideline':'Reactivate')+'</button><button class="small danger" data-routine-delete="'+di+'">Delete</button></div>';
 if(!collapsed){html+='<div class="add-row"><select data-ex-select="'+di+'">'+exerciseChoiceHtml()+'</select><button class="small gold" data-addex="'+di+'">Add From Library</button></div>';
 d.exercises.forEach(function(pe,ei){var e=plan(pe); html+='<div class="card compact-ex"><div><b>'+esc(e.name)+'</b><div class="muted">'+(e.type==='cardio'?esc(pe.durationSec||e.defaultDurationSec||0)+' sec':esc(pe.weight||e.defaultWeight||0)+' lb · '+esc(pe.sets||e.defaultSets||0)+' sets · '+esc(pe.reps||e.defaultReps||0)+' reps · rest '+restFmt(pe.restSec||e.defaultRestSec||0))+'</div></div><div class="exercise-actions"><button class="small" data-edit-lib="'+di+','+ei+'">Edit</button><button class="small" data-ex-up="'+di+','+ei+'">↑</button><button class="small" data-ex-down="'+di+','+ei+'">↓</button><button class="small danger" data-del="'+di+','+ei+'">Remove</button></div></div>';});}
 html+='</div>';});
 $('tab-routine').innerHTML=html;
 $('newRoutine').onclick=createRoutine; $('syncRoutine').onclick=syncPush;
 document.querySelectorAll('[data-collapse-routine]').forEach(function(b){b.onclick=function(){var d=state.routine.days[Number(b.dataset.collapseRoutine)]; if(!d)return; routineCollapsed[d.id]=!isRoutineCollapsed(d.id); renderRoutine();};});
 document.querySelectorAll('[data-del]').forEach(function(b){b.onclick=function(){var p=b.dataset.del.split(',').map(Number); state.routine.days[p[0]].exercises.splice(p[1],1); saveLocal(); render();};});
 document.querySelectorAll('[data-addex]').forEach(function(b){b.onclick=function(){var di=Number(b.dataset.addex); var sel=document.querySelector('[data-ex-select="'+di+'"]'); addExerciseToRoutine(di,sel&&sel.value);};});
 document.querySelectorAll('[data-edit-lib]').forEach(function(b){b.onclick=function(){var p=b.dataset.editLib.split(',').map(Number); var pe=state.routine.days[p[0]]&&state.routine.days[p[0]].exercises[p[1]]; if(pe)openExerciseEditor(pe.exerciseId,{routineIndex:p[0],exerciseIndex:p[1]});};});
 document.querySelectorAll('[data-routine-rename]').forEach(function(b){b.onclick=function(){renameRoutine(Number(b.dataset.routineRename));};});
 document.querySelectorAll('[data-routine-toggle]').forEach(function(b){b.onclick=function(){toggleRoutine(Number(b.dataset.routineToggle));};});
 document.querySelectorAll('[data-routine-delete]').forEach(function(b){b.onclick=function(){deleteRoutine(Number(b.dataset.routineDelete));};});
 document.querySelectorAll('[data-routine-up]').forEach(function(b){b.onclick=function(){moveRoutine(Number(b.dataset.routineUp),-1);};});
 document.querySelectorAll('[data-routine-down]').forEach(function(b){b.onclick=function(){moveRoutine(Number(b.dataset.routineDown),1);};});
 document.querySelectorAll('[data-ex-up]').forEach(function(b){b.onclick=function(){var p=b.dataset.exUp.split(',').map(Number); moveExercise(p[0],p[1],-1);};});
 document.querySelectorAll('[data-ex-down]').forEach(function(b){b.onclick=function(){var p=b.dataset.exDown.split(',').map(Number); moveExercise(p[0],p[1],1);};});
}
function createRoutine(){var name=prompt('Name for the new routine:','New Routine'); if(!name)return; state.routine.days.push({id:'routine-'+Date.now().toString(36),name:name.trim()||'New Routine',notes:'',active:true,exercises:[]}); saveLocal(); render(); toast('Routine created. Add exercises from the library.');}
function renameRoutine(di){var d=state.routine.days[di]; if(!d)return; var name=prompt('Rename routine:',d.name); if(!name)return; d.name=name.trim()||d.name; saveLocal(); render();}
function toggleRoutine(di){var d=state.routine.days[di]; if(!d)return; var wasActive=d.active!==false; d.active=!wasActive; state.routine.rotationIndex=0; saveLocal(); syncPush(); render(); toast(d.active===false?'Routine sidelined and removed from rotation.':'Routine reactivated and returned to rotation.');}
function deleteRoutine(di){var d=state.routine.days[di]; if(!d)return; if(!confirm('Delete routine "'+d.name+'"? This does not delete workout history.'))return; state.routine.days.splice(di,1); state.routine.rotationIndex=0; saveLocal(); render();}
function moveRoutine(di,delta){var arr=state.routine.days, ni=di+delta; if(ni<0||ni>=arr.length)return; var tmp=arr[di]; arr[di]=arr[ni]; arr[ni]=tmp; state.routine.rotationIndex=0; saveLocal(); render();}
function addExerciseToRoutine(di,id){var e=ex(id); if(!e.id){toast('Choose a valid exercise.');return;} var pe={exerciseId:id,weight:e.defaultWeight||0,sets:e.defaultSets||1,reps:e.defaultReps||0,restSec:e.defaultRestSec||0}; if(e.type==='cardio')pe.durationSec=e.defaultDurationSec||300; state.routine.days[di].exercises.push(pe); saveLocal(); render();}
function moveExercise(di,ei,delta){var arr=state.routine.days[di]&&state.routine.days[di].exercises, ni=ei+delta; if(!arr||ni<0||ni>=arr.length)return; var tmp=arr[ei]; arr[ei]=arr[ni]; arr[ni]=tmp; saveLocal(); render();}
function renderLibrary(){var html='<div class="panel"><h2>Exercise Library</h2><p class="muted">Edit default weight, sets, reps, and rest here. These defaults are used when adding exercises to routines. Existing routine exercises can be updated from the edit modal.</p></div>'; state.exerciseLibrary.forEach(function(e){html+='<div class="card"><div class="row"><div><b>'+esc(e.name)+'</b><div class="muted">ID: '+esc(e.id)+' · '+esc(e.type)+'</div></div><button class="small gold" data-lib-edit="'+esc(e.id)+'">Edit</button></div><div class="muted">Default: '+(e.type==='cardio'?esc(e.defaultDurationSec||0)+' sec':esc(e.defaultWeight||0)+' lb · '+esc(e.defaultSets||0)+' sets · '+esc(e.defaultReps||0)+' reps · rest '+restFmt(e.defaultRestSec||0))+'</div>'+(e.sourceUrl?'<a class="linkbtn" target="_blank" rel="noopener" href="'+esc(e.sourceUrl)+'">Reference</a>':'')+'<div>'+(e.equipment||[]).map(function(x){return '<span class="pill">'+esc(x)+'</span>';}).join('')+'</div></div>';}); $('tab-library').innerHTML=html; document.querySelectorAll('[data-lib-edit]').forEach(function(b){b.onclick=function(){openExerciseEditor(b.dataset.libEdit,null);};});}
function openExerciseEditor(exerciseId,source){var e=ex(exerciseId); if(!e.id){toast('Exercise not found.');return;} var overlay=document.createElement('div'); overlay.className='modal-backdrop'; var routineNote=''; if(source)routineNote='<label class="checkrow"><input id="exApplyRoutine" type="checkbox" checked> Also update this routine exercise with these values</label>';
 overlay.innerHTML='<div class="modal-card"><div class="row"><div><h2>Edit Exercise</h2><div class="muted">'+esc(e.name)+'</div></div><button id="exClose" class="ghost">×</button></div><div class="grid two"><label>Name<input id="exName" value="'+esc(e.name)+'"></label><label>Type<select id="exType"><option value="strength">Strength</option><option value="cardio">Cardio</option><option value="mobility">Mobility</option></select></label><label>Default weight<input id="exWeight" inputmode="decimal" value="'+esc(e.defaultWeight||0)+'"></label><label>Default sets<input id="exSets" inputmode="numeric" value="'+esc(e.defaultSets||1)+'"></label><label>Default reps<input id="exReps" inputmode="numeric" value="'+esc(e.defaultReps||0)+'"></label><label>Default rest seconds<input id="exRest" inputmode="numeric" value="'+esc(e.defaultRestSec||0)+'"></label><label>Default duration seconds<input id="exDur" inputmode="numeric" value="'+esc(e.defaultDurationSec||0)+'"></label><label>Source/reference URL<input id="exUrl" value="'+esc(e.sourceUrl||'')+'"></label></div><label>Notes / cues<textarea id="exNotes">'+esc((e.cues||e.notes||[]).join ? (e.cues||[]).join('\n') : (e.notes||''))+'</textarea></label>'+routineNote+'<div class="grid two" style="margin-top:12px"><button id="exSave" class="gold">Save Exercise</button><button id="exCancel" class="ghost">Cancel</button></div></div>'; document.body.appendChild(overlay); $('exType').value=e.type||'strength'; function close(){overlay.remove();}
 $('exClose').onclick=close; $('exCancel').onclick=close; overlay.onclick=function(ev){if(ev.target===overlay)close();}; $('exSave').onclick=function(){e.name=$('exName').value.trim()||e.name; e.type=$('exType').value; e.defaultWeight=Number($('exWeight').value)||0; e.defaultSets=Math.max(0,Number($('exSets').value)||0); e.defaultReps=Math.max(0,Number($('exReps').value)||0); e.defaultRestSec=Math.max(0,Number($('exRest').value)||0); e.defaultDurationSec=Math.max(0,Number($('exDur').value)||0); e.sourceUrl=$('exUrl').value.trim(); e.cues=$('exNotes').value.split('\n').map(function(x){return x.trim();}).filter(Boolean); if(source&&$('exApplyRoutine')&&$('exApplyRoutine').checked){var pe=state.routine.days[source.routineIndex]&&state.routine.days[source.routineIndex].exercises[source.exerciseIndex]; if(pe){pe.weight=e.defaultWeight; pe.sets=e.defaultSets; pe.reps=e.defaultReps; pe.restSec=e.defaultRestSec; if(e.type==='cardio')pe.durationSec=e.defaultDurationSec;}} saveLocal(); syncPush(); close(); render(); toast('Exercise updated.');};}
function renderHistory(){var ss=(state.sessions||[]).slice().reverse(); var html='<div class="panel"><h2>History</h2><p class="muted">'+ss.length+' workout sessions logged.</p></div>'; ss.slice(0,50).forEach(function(s){var skipped=s.skippedWorkout||s.status==='skipped'; var detail=skipped?'Skipped · rotation advanced':(Math.round(s.durationSec/60)+' min · '+(s.logs||[]).length+' sets'); html+='<div class="card"><div class="row"><div><b>'+esc(s.dayName)+(skipped?' <span class="pill">Skipped</span>':'')+'</b><div class="muted">'+new Date(s.endedAt).toLocaleString()+' · '+detail+'</div></div><button class="small danger" data-delete-session="'+esc(s.id)+'">Delete</button></div></div>';}); $('tab-history').innerHTML=html; document.querySelectorAll('[data-delete-session]').forEach(function(b){b.onclick=function(){deleteSession(b.dataset.deleteSession);};});}
function deleteSession(id){var s=(state.sessions||[]).find(function(x){return String(x.id)===String(id);}); if(!s)return; if(!confirm('Delete workout history entry "'+s.dayName+'"? Existing RQ contracts/gold will not be changed.'))return; state.sessions=state.sessions.filter(function(x){return String(x.id)!==String(id);}); saveLocal(); syncPush(); render(); toast('Workout history entry deleted.');}
function renderBody(){var html='<div class="panel"><h2>Body Measurements</h2><div class="grid two"><label>Body weight<input id="bodyWeight" inputmode="decimal"></label><label>Waist<input id="waist" inputmode="decimal"></label><label>Bicep<input id="bicep" inputmode="decimal"></label><label>Chest<input id="chest" inputmode="decimal"></label><label>Thigh<input id="thigh" inputmode="decimal"></label><label>Notes<input id="bodyNotes"></label></div><button id="saveBody" class="wide" style="margin-top:10px">Log Measurements</button></div>'; (state.bodyLog||[]).slice().reverse().slice(0,20).forEach(function(b){html+='<div class="card"><b>'+new Date(b.at).toLocaleDateString()+'</b><div class="muted">Weight '+esc(b.weight||'—')+' · Waist '+esc(b.waist||'—')+' · Bicep '+esc(b.bicep||'—')+'</div><div>'+esc(b.notes||'')+'</div></div>';}); $('tab-body').innerHTML=html; $('saveBody').onclick=function(){state.bodyLog.push({at:new Date().toISOString(),weight:$('bodyWeight').value,waist:$('waist').value,bicep:$('bicep').value,chest:$('chest').value,thigh:$('thigh').value,notes:$('bodyNotes').value}); saveLocal(); syncPush(); render();};}
function bind(){ $('backToRq').onclick=function(){location.href='../relentless-quest-in-development.html';}; $('syncBtn').onclick=function(){syncPush();}; document.querySelectorAll('.tabs button').forEach(function(b){b.onclick=function(){document.querySelectorAll('.tabs button').forEach(function(x){x.classList.remove('active')}); b.classList.add('active'); document.querySelectorAll('.tab-panel').forEach(function(x){x.classList.add('hidden')}); $('tab-'+b.dataset.tab).classList.remove('hidden');};});}
window.RQFit={startWorkout:startWorkout,skipNextWorkout:skipNextWorkout}; bind(); syncPull();
})();
